repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.386
    hooks:
      - id: checkov
        args: ["-d", "."]
