name: terraform-ci
on:
  pull_request:
    branches: [ main ]
    paths: [ '**/*.tf', '.terraform.lock.hcl', 'modules/**' ]
  push:
    branches: [ main ]
    paths: [ '**/*.tf', '.terraform.lock.hcl', 'modules/**' ]
permissions:
  id-token: write
  contents: read
jobs:
  validate-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
      - uses: aquasecurity/tfsec-action@v1.0.5
        with: { soft_fail: false }
      - uses: bridgecrewio/checkov-action@v12
        with: { directory: . }

  plan:
    if: github.event_name == 'pull_request'
    needs: [validate-security]
    runs-on: ubuntu-latest
    env: { AWS_REGION: us-east-1 }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC_TERRAFORM }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform plan -out=plan.out -input=false -no-color
      - uses: actions/upload-artifact@v4
        with: { name: tfplan, path: plan.out }

  apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [validate-security]
    runs-on: ubuntu-latest
    environment: { name: production }
    env: { AWS_REGION: us-east-1 }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_OIDC_TERRAFORM }}
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init -input=false
      - run: terraform apply -auto-approve -input=false
